### ISSUE TITLE
An options for Boundary intersection detection

### ISSUE THREAD

**Issue by DRKWang** [kip-hart/AABBTree#13] opened 2021-05-29 01:53 UTC
Hi, I am working on a project about polyhedra intersection detection. Your AABBTree module is quite helpful and essential for my project. The open box intersection detection looks good most time, however, it seems a little blurry when it is working on closed box (including the boundaries) intersection detection. For example, the following code only works for open box intersection detection, but it does not work for closed box, otherwise, it should return ['box1', 'box 2']

```
from aabbtree import AABB
from aabbtree import AABBTree 
tree = AABBTree()
aabb1 = AABB([(0, 0)])
aabb2 = AABB([(-1, 0)])
tree.add(aabb1, 'box 1')
tree.add(aabb2, 'box 2')
tree.overlap_values(aabb2)
>>>['box 2']
```

Could you add an argument to indicate whether it is overlapping in terms of open or closed boxes in the ```overlap_values()``` method?

**Comment by kip-hart** [comment] 2021-05-29 02:43
Hi @DRKWang, sure thing. I've created a branch and will add an optional flag to specify open vs closed intersection. Thanks for the suggestion - it shouldn't take more than a day or two to implement and release.

**Comment by kip-hart** [comment] 2021-05-29 04:07
I added the `closed=True` option to the `AABB.overlap` method as well as `AABBTree.does_overlap`, `AABBTree.overlap_aabbs`, and `AABBTree.overlap_values`. Upgrade aabbtree to version 4.7.0 to get this optional flag.

Thanks again for the suggestion! Feel free to re-open if the issue isn't resolved.

**Closed by kip-hart** 2021-05-29 04:07 UTC

**Comment by DRKWang** [comment] 2021-05-29 16:10
> I added the `closed=True` option to the `AABB.overlap` method as well as `AABBTree.does_overlap`, `AABBTree.overlap_aabbs`, and `AABBTree.overlap_values`. Upgrade aabbtree to version 4.7.0 to get this optional flag.
> 
> Thanks again for the suggestion! Feel free to re-open if the issue isn't resolved.

Thanks for your help. It will be really helpful.
